### PR TITLE
Made code not as bad

### PR DESCRIPTION
**Pull request by sophiethefox**
moved everything to one command, added tab completion, reformatted code, added myself to credits :), only tested the boopback

### CODE REVIEW

**Comment by sophiethefox** [comment]
I really haven't tested much as I don't like spamming people.
So even though it should all be working as I really only changed the commands, the migration from Java 6 > 8 along with making some variables final could have affected it.

**Comment by Miqhtiedev** [comment]
i'll test it all now and merge if it all works

**Comment by ryanArora** [comment]
lol

**Comment by ryanArora** [comment]
bump

**Comment by ghost** [comment]
think miqhtie died

**Pull request merged**
